const todo = {
  STORAGE_KEY: 'todos',
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: 'DELETE_TODO',
  EDIT_TODO: 'EDIT_TODO',
  UPDATE_TODO_STATE: 'UPDATE_TODO_STATE',
  CLEAR_ALL_TODO: 'CLEAR_ALL_TODO'
}

export {todo}
